### ISSUE TITLE
Existing work

### ISSUE THREAD

**Issue by Xemrox** [WorksOfBarry/luaILE#1]
@WorksOfBarry nice to see you working on this!
My time is limited but referring to stockholm there is some work allready done in this field.
Have a look here:
http://lua4z.com/

**Comment by worksofliam** [comment]
@Xemrox Nice, thanks! Will look into getting this running!

Edit: Is there not any source provided for this project?

**Comment by Xemrox** [comment]
Ohh too bad.

> Lua4z is not open source. The extension libraries developed for Lua4z are not open source.

Straight from their doc.
http://lua4z.com/doc/manual/introduction.md.html

**Comment by worksofliam** [comment]
Damn, that sucks!
